### ISSUE TITLE
Question about application of this script!

### ISSUE THREAD

**Issue by Milkbad** [lemasato/Non-Steam-Overlay-Manager#1]
I followed the steps for this script the first time and it successfully asked me to select the launcher and the client after activating the shortcut. BUT i accidentally selected the wrong client file. After starting over and adding an attempt to launch the vbs script, the command prompt that asks me to select the launcher and the client now instantly closes.

Is there a way to fix this issue so i cant properly re-select the correct client?

**Comment by lemasato** [comment]
There should be a SteamOverlayFix.ini in the same folder.  
Deleting it will effectively reset your settings.

**Comment by Milkbad** [comment]
Would you be willing to take the time to assist me in figuring out how to set this up for a particular game?

I select the Launcher and the Client, but when it starts, the script kills the process and the overlay does not occur in-game.

Its pertaining to a game called MxM, using the NC Launcher.

**Comment by lemasato** [comment]
I'll download it overnight and see if I can get it working c:
(This script was written quite a long time ago, for a friend... It's not very user-friendly. But seeing as how some people seem to like it, I'll try to update it as soon as I can.)

**Comment by lemasato** [comment]
After some testings, this game does not seem to work with the Steam Overlay.  
Even renaming the MXMClient.bin file to .exe and adding it directly to Steam failed.

Alternatively, you could add the launcher to steam and run the game from it but it will only serve to tell your friends what you are playing.

**Comment by Milkbad** [comment]
Thank you for tinkering along with me. I contacted their support staff with
no assurance that they could give me about outside overlays/streaming
services being applicable.

Any idea how exactly they managed to keep the MxMCleint.exe from allowing
to connect to their servers without the launcher launching the .exe? I
haven't been able to figure out exactly how they were able to do that at
all.

**Comment by lemasato** [comment]
> how exactly they managed to keep the MxMCleint.exe from allowing
to connect to their servers without the launcher launching the .exe?

What do you mean?

Searching through the game's subreddit, I found a few results: [Search](https://www.reddit.com/r/PlayMXM/search?q=steam&restrict_sr=on)  
It seems the file renaming workaround was working until they hotfixed it a few days ago. There is nothing that can be done about it, until they decide to allow external overlays.

**Comment by Milkbad** [comment]
After launching MxMCleint.exe to start the game, upon getting the game
started, it will ask for a login, but if the attempt is made the game will
not connect to NCSoft servers.

If the game is launched, though NCLauncher and loads up, there is no log-in
process and the servers are easily connected to.

How exactly do they keep the .exe (when launched directly) from connecting
to their servers. I couldnt find an actual reason when picking apart the
MxMClient.exe, to not establith a connection to the NCSeoft servers.

Any ideas why?

**Comment by lemasato** [comment]
They could have disabled manual logging, or something.
People says it was working a few days ago... not sure why they (NCSOFT) would do this.

**Comment by lemasato** [comment]
Hey there, it's been quite a while.  
I have made a complete new thing. If you are still interested, you can download it on the [https://github.com/lemasato/Non-Steam-Overlay-Manager/releases](releases) tab. Since this game does not seem to allow the Steam Overlay normally, you will have to enable the "Use External Overlay" setting.

I'm not sure if you are still around, so I'll be closing this issue for now.  
If you have any question or need support, I'll be happy to provide the help.
