### ISSUE TITLE
[Help] How can i add valorant?

### ISSUE THREAD

**Issue by robinhugy** [lemasato/Non-Steam-Overlay-Manager#14]
Nice tool, but i have problem with valorant.
Can you (or somebody) help how can i use with valorant?

Tried to add Riot Games\Riot Client\RiotClientServices.exe like launcher (get an error)
added normally, no error but no working

launch parameters: --launch-product=valorant --launch-patchline=live

**Comment by lemasato** [comment]
What do you use to start Valorant? If it's a game patcher (like MMOs usually use), then you need to put that as "Launcher location" and tick the corresponding checkbox. Then once the game is started use Windows Task Manager to figure out the game executable and put that as "Client location".

- Patcher as "Launcher location". Using a shortcut should be fine too.
- Game executable as "Client location". Using a shortcut should be fine too.
- Tick "Use NSO Overlay"
- Untick "Restrict NSO Overlay shortcut..."
- "Steam Overlay Shortcut" as whatever you normally use to open Steam Overlay
- "NSO Overlay Shortcut" as whatever you want to use to open the NSO Overlay, needs to be different from Steam Overlay Shortcut
- Add NSO Manager as a non-steam game
- Change the newly added non-steam game launch option to `/Profile="Something"`


Example
![image](https://user-images.githubusercontent.com/14184969/96168482-183e3700-0f21-11eb-9fc0-74e11ad3504c.png)
