### ISSUE TITLE
Error While Installing on FF IX

### ISSUE THREAD

**Issue by Amorphist** [lemasato/Non-Steam-Overlay-Manager#3]
![image](https://user-images.githubusercontent.com/34500443/33923722-bb7d1f3e-dfa0-11e7-9a04-ea6a51f17c2d.png)

This happens upon "Killing Game Instance"

**Comment by lemasato** [comment]
Windows 10?
The script was running just fine on W7 back when I made it. But since I switched to W10 and decided to give it a try again, it kept throwing errors.  
I'm working on a new version that is much easier to use. It's close to being ready for public-release, but I need to find some games to try it out.

**Comment by Amorphist** [comment]
Yes, Windows 10, exactly. 

If you'd like me to help bug test, I gladly would. I love my Steam Controller but getting it to work with anything that has issue with the overlay is such a headache. As of right now I swap between drivers; there's one floating out there that tricks the system into thinking it's just a Xbox 360 controller and that's no fun.

**Comment by lemasato** [comment]
It's out now, you can download it over the [releases](https://github.com/lemasato/Non-Steam-Overlay-Manager/releases) tab.  
I do not know how the Steam Overlay works with this game. You may have to enable the "Use External Overlay" setting. I'll be leaving this open, hope to get some feedback!

**Comment by Amorphist** [comment]
So far no issues! Thanks a lot

**Comment by lemasato** [comment]
I'll be closing this.
If you ever have any question, know that you can contact me and I'll respond as soon as possible!
