### ISSUE TITLE
Game.exe doesn't launch

### ISSUE THREAD

**Issue by yoongjun** [lemasato/Non-Steam-Overlay-Manager#5]
First of all thank you for the new release of NSO, love that you followed up with this project I personally really appreciate it.

I've tried the steps but the game/launcher doesn't seem to launch when I launch the exe from steam. It only launches NSO-Manager.exe when I launch it from steam

https://imgur.com/a/0W4w1

Am I doing it right?

**Comment by lemasato** [comment]
You seem to have added a space between the `e` of /Profile and `=`, making it `/Profile =` when it should be `/Profile=`. Or am I mistaken here?

**Comment by yoongjun** [comment]
Totally my bad, I didn't noticed the space. Thanks for the help

**Comment by lemasato** [comment]
Glad I could help!
