### ISSUE TITLE
Can't remove (or do anything) to profile

### ISSUE THREAD

**Issue by yoongjun** [lemasato/Non-Steam-Overlay-Manager#6]
I created a new profile but everytime I click any of the buttons, it gives me the error which says that.

Profile "BD" is invalid.
Path for Client does not exist:
Path for Launcher does no exist:

I can't seem to add the launcher or do anything at all without this error popping out.
Even trying to delete the profile gives me the error.

**Comment by lemasato** [comment]
Confirmed. My bad.

**Comment by lemasato** [comment]
Here we go, [0.2.1 released](https://github.com/lemasato/Non-Steam-Overlay-Manager/releases/tag/0.2.1)!  
I'm sorry, that was a (very) stupid mistake of mine.

Thank you for reporting!
