### ISSUE TITLE
Launch Option

### ISSUE THREAD

**Issue by andremeireles** [lemasato/Non-Steam-Overlay-Manager#7]
I would like to use this manager for an application instead a game.
How to tell to NSO pass a launch option to the application? It's possible?
For example, "C:\path\to\application\abc.exe" -disable_feature_at_startup

**Comment by lemasato** [comment]
Not possible as of now.  
Will make sure to release an update including this!

**Comment by lemasato** [comment]
Hey,
This feature is finally out.
You can read the full changelogs [over here](https://github.com/lemasato/Non-Steam-Overlay-Manager/releases/tag/0.2.3)

In your case, this is how you would have to set it up:
1. Create a new profile (Example "My App").
1. Untick the launcher checkbox.
1. Click on the "Client location" browse button and select your application executable.
1. Add your -disable_feature_at_startup to the "Launch parameters" edit field.

You may also want to use a .lnk file that already has the cmd-line parameters included and then use that file as your "Client location".

**Comment by andremeireles** [comment]
Very good indeed.
Thank you very much for including my suggestion.
