### ISSUE TITLE
NSO Overlay Not Working

### ISSUE THREAD

**Issue by dotaxis** [lemasato/Non-Steam-Overlay-Manager#9]
I initially thought this was a problem with Windows Store games but have now tested the NSO with a few other games (didn't need it until trying to get Sea of Thieves working).

With Windows Store games, I can get the games to launch through Steam but when I press my NSO Overlay shortcut it just locks up my mouse and keyboard and I have to CTRL-ALT-DEL to even tab out.

In other non-Steam games it just blacks out my screen completely and sometimes minimizes the game after several seconds.

Everything works fine but I want to use the Steam overlay with Sea of Thieves and I'm not sure what's wrong here.

Windows 10 Pro Version 1803

Have tried running the overlay, steam, and the main NSO overlay program with and without elevated privileges. At a real loss here.

**Comment by lemasato** [comment]
>it just blacks out my screen completely and sometimes minimizes the game after several seconds  

Are you running your games in borderless?
The NSO Overlay is an external application that will get on top of your game. It is not hooked into the process, so if your game is not running in borderless mode, you will be tabbed out of the game.

For WinStore games, make sure to have the *"Restrict NSO Overlay shortcut to the game window only"* **disabled**.

**Comment by dotaxis** [comment]
Oh. I guess the overlay does indeed work, but Sea of Thieves doesn't have a borderless fullscreen option. How'd you get it working?

**Comment by lemasato** [comment]
Is there no Windowed mode either?
If there is, you could use that and try this script:
```
#SingleInstance, Force
#KeyHistory 0
#NoEnv
ListLines, Off

F11::WindowedBorderless()

WindowedBorderless() {
	WinGet, winID, ID, A
	WinGet, winStyle, Style, ahk_id %winID%

	if (winStyle & 0xC40000)
		WinSet, Style, -0xC40000, ahk_id %winID%
	else
		WinSet, Style, +0xC40000, ahk_id %winID%

	WinMove, ahk_id %winID%, , 0, 0,% A_ScreenWidth,% A_ScreenHeight
	WinSet, AlwaysOnTop, Off, ahk_id %winID%
}
```

Save as .ahk and run the script (make sure to have [AutoHotKey](https://autohotkey.com/download/ahk-install.exe) installed).
Press F11 once to toggle borderless, press another time to revert to windowed.
Note: There are some games where this trick doesn't work.

**Comment by dotaxis** [comment]
Unfortunately no dice there. Doesn't hide the border of the window. Fullscreenizer did the same thing.

At any rate I guess this isn't really an issue with your code and Sea of Thieves just sucks.

I really hate Microsoft sometimes. Thanks for trying anyhow!
